cmake_minimum_required(VERSION 3.18)
project(mandelbrot C)

include(CheckLanguage)
check_language(CUDA)
if(CMAKE_CUDA_COMPILER)
    option(CUDA "Enable CUDA" ON)
else()
    option(CUDA "Enable CUDA" OFF)
endif()

set(CMAKE_C_STANDARD 17)
set(CMAKE_C_EXTENSIONS ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON) # for clangd
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE Debug)
endif()
add_compile_options(-Wall -pipe)
#add_compile_options("$<$<CONFIG:Debug>:-ggdb3;-O0;-Wpedantic;-Wextra>")
add_compile_options("$<$<CONFIG:Debug>:-ggdb3;-O0>")
add_compile_options("$<$<NOT:$<CONFIG:Debug>>:-O3;-ffast-math;-fomit-frame-pointer;-fno-finite-math-only;-ftree-vectorize>")

find_package(PkgConfig REQUIRED)
pkg_check_modules(SDL2 REQUIRED IMPORTED_TARGET sdl2 SDL2_image)
find_package(GLEW REQUIRED)
find_package(OpenGL REQUIRED)
if(APPLE) # Apple clang needs brew's libomp
  execute_process(COMMAND brew --prefix libomp OUTPUT_VARIABLE OpenMP_ROOT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
endif()
find_package(OpenMP)
find_library(GMP gmp REQUIRED)

add_executable(mandelbrot mandelmain.c mandelcpu.c)
target_link_libraries(mandelbrot PkgConfig::SDL2 GLEW::GLEW OpenGL::GL ${GMP} m)
if(OpenMP_C_FOUND)
    target_link_libraries(mandelbrot OpenMP::OpenMP_C)
endif()
set_property(TARGET mandelbrot PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)

if(APPLE AND CMAKE_C_COMPILER_ID STREQUAL "GNU" AND CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
    # homebrew gcc on MacOS rejects -march=native
    target_compile_options(mandelbrot PRIVATE -mcpu=native)
else()
    target_compile_options(mandelbrot PRIVATE -march=native -mtune=native)
endif()
target_link_libraries(mandelbrot stdc++)

if(CUDA)
    if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
        set(CMAKE_CUDA_ARCHITECTURES native)
    endif()
    enable_language(CUDA)
    find_package(CUDAToolkit REQUIRED)
    add_library(mandelcuda STATIC mandelcuda.cu)
    set_target_properties(mandelcuda PROPERTIES
        CUDA_SEPARABLE_COMPILATION ON
        CUDA_RESOLVE_DEVICE_SYMBOLS ON)
    target_compile_options(mandelcuda PRIVATE "$<$<NOT:$<CONFIG:Debug>>:-O3>")
    set_target_properties(mandelbrot PROPERTIES CUDA_ARCHITECTURES "${CMAKE_CUDA_ARCHITECTURES}")
    target_compile_definitions(mandelbrot PRIVATE USE_CUDA)
    target_link_libraries(mandelbrot mandelcuda CUDA::cudart)
endif()
